
# General.
epochs: 10
seed: 0
steps: 5000000
eval_every: 10000
log_every: 1000
log_scalars: True
log_images: True
gpu_growth: True
precision: 16

# Environment.
task: dmc_walker_walk
envs: 1
parallel: 'none'
action_repeat: 2
time_limit: 1000
prefill: 5000
eval_noise: 0.0
clip_rewards: 'none'

# Model.
deter_size: 200
stoch_size: 30
num_units: 400
dense_act: 'elu'
cnn_act: 'relu'
cnn_depth: 32
pcont: False
free_nats: 3.0
kl_scale: 1.0
pcont_scale: 10.0
weight_decay: 0.0
weight_decay_pattern: r'.*'

# Training.
batch_size: 50
batch_length: 50
train_every: 1000
train_steps: 100
pretrain: 100
model_lr: 0.0006
value_lr: 0.00008
actor_lr: 0.00008
grad_clip: 100.0
dataset_balance: False

# Behavior.
discount: 0.99
disclam: 0.95
horizon: 15
action_dist: 'tanh_normal'
action_init_std: 5.0
expl: 'additive_gaussian'
expl_amount: 0.3
expl_decay: 0.0
expl_min: 0.0